stages:
  - build
  - test
  - deploy

stage_build:
    stage: build
    image: ubuntu:20.04
    tags:
        - build
    script:
        - mkdir build
        - cp folder.sh build/
        - cd build
        - echo "folders_count=10" >> folder.sh
        - echo "path_to_save=/home/shredder/folder_script/" >> folder.sh
        - echo "" >> $path_to_save/folder.sh
        - echo "current_date=\$(date +%Y.%m.%d)" >> folder.sh
        - echo "" >> $path_to_save/folder.sh
        - echo "for ((i=1;i<=\$folders_count;i++)); do" >> folder.sh
        - echo "  folder_name=\"\${current_date}_Папка\$i\"" >> folder.sh
        - echo "  mkdir -p \"\$path_to_save/\$folder_name\"" >> folder.sh
        - echo "done" >> folder.sh
        - echo "" >> folder.sh
        - echo "echo \"Script finished in \$(date)\" >> \$path_to_save/script.log" >> folder.sh
    artifacts:
        paths:
          - build/

stage_test:
  stage: test
  image: ubuntu:20.04
  tags:
    - test
  script:
    - echo "Running tests..."
    - mkdir test_dir
    - cp $CI_PROJECT_DIR/build/folder.sh test_dir/
    - cd test_dir
    - chmod +x folder.sh
    - ./folder.sh &> ../test_dir/test_result.log
    - echo "Tests finished."
  artifacts:
    paths:
      - test_dir/
      - test_dir/test_result.log

stage_deploy:
  stage: deploy
  image: ubuntu:20.04
  tags:
    - deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )' 
    - eval $(ssh-agent -s) > /dev/null 2>&1
    - ssh-add <(echo "$SSH_PRIVATE_KEY") > /dev/null 2>&1
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts' 

  script:
    - echo "Deploying to VPS..."
    - ssh -i "$SSH_PRIVATE_KEY" -o StrictHostKeyChecking=no -t $SSH_USER@$SSH_IP "mkdir -p $SSH_DEPLOY_PATH" > /dev/null 2>&1
    - scp -i "$SSH_PRIVATE_KEY" -o StrictHostKeyChecking=no "$CI_PROJECT_DIR/build/folder.sh" $SSH_USER@$SSH_IP:$SSH_DEPLOY_PATH/folder.sh > /dev/null 2>&1
    - echo "Deployment finished."

